Cargo class constructors & getters added
Marimeiko/object-oriented-programming pull request #26
Opened 2020-06-19 16:49 UTC by mariuszlisowski

2020-06-20 11:12 UTC, Petrus9107 commented on shm/cargo.cpp
> +std::string Cargo::getName() { return name_; }
best practise is to use "const getters" -> std::string Cargo::getName() **const** { return name_;), same to the rest of getters

2020-06-20 11:12 UTC, Petrus9107 commented on shm/cargo.cpp
> +void Cargo::setName(std::string name) { name_ = name; }
should pass setters arguments by reference

2020-06-21 10:43 UTC, mariuszlisowski commented on shm/cargo.cpp
> +std::string Cargo::getName() { return name_; }
That's right!

2020-06-22 12:35 UTC, m-kop requested changes

2020-06-22 12:35 UTC, m-kop commented on shm/cargo.cpp
> +void Cargo::setName(std::string name) { name_ = name; }
please add const &

2020-06-22 12:35 UTC, m-kop commented on shm/cargo.hpp
> +    Cargo();
is there a use case for default constructor? I'm asking as I cannot figure it out

2020-06-22 13:00 UTC, m-kop approved these changes

2020-06-22 19:20 UTC, merged