Adding CMake compilation support
Marimeiko/object-oriented-programming pull request #28
Opened 2020-06-21 14:39 UTC by Petrus9107

2020-06-21 18:16 UTC, m-kop commented on shm/CMakeLists.txt
> +add_test(NAME shm_test COMMAND ${CMAKE_PROJECT_NAME}-ut)
new line

2020-06-21 22:31 UTC, m-kop requested changes

2020-06-21 22:31 UTC, m-kop commented on shm/CMakeLists.txt
> +add_test(NAME shm_test COMMAND ${CMAKE_PROJECT_NAME}-ut)
new line

2020-06-21 22:31 UTC, m-kop commented on shm/CMakeLists.txt
> +    ${CMAKE_SOURCE_DIR}/Map.cpp
remove these or add main.cpp to the PR

2020-06-21 22:31 UTC, m-kop commented on shm/CMakeLists.txt
> +add_executable(${CMAKE_PROJECT_NAME}-ut ${SOURCES} test.cpp)
ditto

2020-06-22 14:29 UTC, Petrus9107 commented on shm/CMakeLists.txt
> +    ${CMAKE_SOURCE_DIR}/Map.cpp
added main.cpp

2020-06-22 14:29 UTC, Petrus9107 commented on shm/CMakeLists.txt
> +add_executable(${CMAKE_PROJECT_NAME}-ut ${SOURCES} test.cpp)
added "empty" test.cpp

2020-06-22 14:29 UTC, Petrus9107 commented on shm/CMakeLists.txt
> +add_test(NAME shm_test COMMAND ${CMAKE_PROJECT_NAME}-ut)
done

2020-06-22 14:29 UTC, Petrus9107 commented on shm/CMakeLists.txt
> +add_test(NAME shm_test COMMAND ${CMAKE_PROJECT_NAME}-ut)
done

2020-06-22 18:13 UTC, merged