add Player class
Marimeiko/object-oriented-programming pull request #30
Opened 2020-06-21 22:18 UTC by m-kop

2020-06-22 20:14 UTC, mariuszlisowski requested changes

2020-06-22 20:14 UTC, mariuszlisowski commented on shm/player.hpp
> +    std::unique_ptr<Ship> getShip() { return std::move(ship_); }
Do we need 'getShip' method?

2020-06-22 20:14 UTC, mariuszlisowski commented on shm/player.hpp
> +
We also need the following methods:
size_t getSpeed() const;
Cargo* getCargo(size_t index) const;

2020-06-22 20:14 UTC, mariuszlisowski commented on shm/player.cpp
> +    ship_ = std::make_unique<Ship>(ship);
Example implementation of 'getSpeed' method:
size_t Player::getSpeed() const { return this->ship_->getSpeed(); }

Example implementation of 'getCargo' method:
Cargo* Player::getCargo(size_t index) const { return ship_->getCargo(index); } **

** Note that get 'getCargo' method has to be implemented in a Ship class as well.

2020-06-22 22:00 UTC, mariuszlisowski requested changes

2020-06-22 22:00 UTC, mariuszlisowski commented on shm/player.cpp
> +}
Please use getCargo(const size_t index) method form Ship class, i.e.  ship_->getCargo(index);

2020-06-22 22:50 UTC, mariuszlisowski approved these changes

2020-06-23 07:37 UTC, m-kop commented
I going to update this PR later on

2020-06-23 23:15 UTC, m-kop commented on shm/player.hpp
> +    std::unique_ptr<Ship> getShip() { return std::move(ship_); }
we were asked to provide getters to members so it's one of them

2020-06-23 23:28 UTC, merged