Task 2.2 - class Fruit
Marimeiko/object-oriented-programming pull request #51
Opened 2020-06-25 19:46 UTC by mariuszlisowski

Driver code included for testing purposes (in test directory)

2020-07-01 12:14 UTC, m-kop requested changes
good work

2020-07-01 12:14 UTC, m-kop commented on shm/inc/fruit.hpp
> +    Fruit(const std::string name, size_t amount, size_t basePrice, size_t timeToSpoil)
const & for string

2020-07-01 12:14 UTC, m-kop commented on shm/src/fruit.cpp
> +    return static_cast<size_t>((static_cast<float>(timeToSpoilLeft_) /
I do't this casting to float is needed, you can change it to timeToSpoilLeft_/ (timeToSpoil_*basePrice_), i.e. make sure multiplication is done first and the division.

2020-07-01 12:14 UTC, m-kop commented on shm/src/fruit.cpp
> +#include "fruit.hpp"
please add fruit.cpp to CMakeLists.txt

2020-07-02 14:30 UTC, mariuszlisowski commented on shm/inc/fruit.hpp
> +    Fruit(const std::string name, size_t amount, size_t basePrice, size_t timeToSpoil)
Right, done.

2020-07-02 14:30 UTC, mariuszlisowski commented on shm/src/fruit.cpp
> +    return static_cast<size_t>((static_cast<float>(timeToSpoilLeft_) /
Without casting to float the price isn't calculated correctly (tested twice). Same with the order of calculations: division must be first then multiplication (otherwise output is zero).

2020-07-02 14:31 UTC, mariuszlisowski commented on shm/src/fruit.cpp
> +#include "fruit.hpp"
Ok

2020-07-02 21:09 UTC, merged