Task 2.3 - class Item
Marimeiko/object-oriented-programming pull request #52
Opened 2020-06-25 19:47 UTC by mariuszlisowski

Driver code included for testing purposes (in test directory)

2020-07-01 12:05 UTC, m-kop requested changes
good work!

2020-07-01 12:05 UTC, m-kop commented on shm/src/item.cpp
> +#include "item.hpp"
please add this file to CMakeLists.txt

2020-07-01 12:05 UTC, m-kop commented on shm/src/item.cpp
> +        const Item* rarityPtr = static_cast<const Item*>(&cargo);
the variable name is misleading

2020-07-01 12:05 UTC, m-kop commented on shm/src/item.cpp
> +        const Item* rarityPtr = static_cast<const Item*>(&cargo);
rarityPtr?

2020-07-01 12:05 UTC, m-kop commented on shm/src/item.cpp
> +        const Item* rarityPtr = static_cast<const Item*>(&cargo);
ditto

2020-07-01 12:07 UTC, m-kop commented on shm/inc/item.hpp
> +    Item(const std::string name, size_t amount, size_t basePrice, Rarity rarity)
const & for string

2020-07-02 14:35 UTC, mariuszlisowski commented on shm/src/item.cpp
> +#include "item.hpp"
Ok

2020-07-02 14:45 UTC, mariuszlisowski commented on shm/inc/item.hpp
> +    Item(const std::string name, size_t amount, size_t basePrice, Rarity rarity)
Right, done.

2020-07-02 15:11 UTC, mariuszlisowski commented on shm/src/item.cpp
> +        const Item* rarityPtr = static_cast<const Item*>(&cargo);
Yes, it is misleading. I can see now. I must had been thinking about the enum class 'rarity' at the moment and left it unchanged. Not it is simply 'item'. Or maybe ptr_item would be better? Let me know if so.

2020-07-02 21:06 UTC, merged