Task 1 - class store() implementation
Marimeiko/object-oriented-programming pull request #58
Opened 2020-07-03 20:02 UTC by Petrus9107

Sharing Task_1 code, for further implementations some remarks still pending (code formatting, my own review etc.)

2020-07-04 11:05 UTC, mariuszlisowski requested changes
Loads of code! Not an easy task. Congrats!

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +    Common::getAvailableSpace(capacity_, cargo_);
return Common::getAvailableSpace(capacity_, cargo_);

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +
one newline redundant

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +
two newlines redundant

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +bool Ship::addCargo(Cargo* cargo) {
void instead of bool

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +bool Ship::removeCargo(Cargo* cargo) {
void instead of bool

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/inc/ship.hpp
> +    bool addCargo(Cargo* cargo);
void instead of bool

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/inc/ship.hpp
> +    bool removeCargo(Cargo* cargo);
void instead of bool

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/inc/player.hpp
> +    bool addCargo(Cargo* cargo) { return ship_->addCargo(cargo); }
void instead of bool and no return

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/inc/player.hpp
> +    bool removeCargo(Cargo* cargo) { return ship_->removeCargo(cargo); }
void instead of bool and no return

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/inc/store.hpp
> +    // bool addCargo(const std::string& name, size_t amount, size_t basePrice);  //overloaded
void instead of bool

2020-07-04 11:05 UTC, mariuszlisowski commented on shm/src/store.cpp
> +bool Store::addCargo(Cargo* cargo) {
void instead of bool

2020-07-04 12:12 UTC, mariuszlisowski commented on shm/inc/common.hpp
> +};
newline at the end

2020-07-04 12:19 UTC, mariuszlisowski commented on shm/src/store.cpp
> +            std::cout << "You cant sell this type of good i stroe." << std::endl;
Message typo error

2020-07-04 13:03 UTC, mariuszlisowski commented on shm/src/ship.cpp
>  }
printCargo() declared in ship.hpp but not implemented. Should be as follows:

void Ship::printCargo() {
    Common::printCargo(cargo_);
}

2020-07-05 11:24 UTC, mariuszlisowski requested changes
Please check formatting in ship.cpp, store.cpp (indentation 2 spaces only).
Comments are redundant, imho.

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/src/store.cpp
> +  }
error: control reaches end of non-void function
Solution: pull the return statement out of the if condition

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/src/store.cpp
> +  }
error: control reaches end of non-void function
Solution: pull the return statement out of the if condition

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/src/cargo.cpp
> +}
newline at the end

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/inc/ship.hpp
> +    void printCargo() {Common::printCargo(cargo_);}
Definition should be in source file

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/inc/ship.hpp
> +    // std::vecto/r<std::shared_ptr<Cargo>> cargo_;
Unused code (not needed)

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +    // If there is not such cargo type yet
Comment redundant

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/src/ship.cpp
> +      // If there is already relevant type of cargo
Comment redundant

2020-07-05 11:24 UTC, mariuszlisowski commented on shm/inc/store.hpp
> +    bool addCargo(Cargo* cargo);
Method repeated (DRY practice violation). Previous definition in ship.cpp. Please check if the method is really needed here.

2020-07-05 13:46 UTC, mariuszlisowski commented on shm/src/store.cpp
> +      player->setMoney(player->getMoney() + totalPrice);
Line doubled

2020-07-05 14:35 UTC, mariuszlisowski approved these changes

2020-07-05 23:11 UTC, m-kop requested changes

2020-07-05 23:11 UTC, m-kop commented on shm/inc/player.hpp
> +    size_t getAvailableSpace() const { return this->ship_->getAvailableSpace(); }
remove this

2020-07-05 23:11 UTC, m-kop commented on shm/src/ship.cpp
> -    }
please do not change these lines

2020-07-05 23:11 UTC, m-kop commented on shm/src/ship.cpp
> -    }
ditto

2020-07-05 23:11 UTC, m-kop commented on shm/src/ship.cpp
> +bool Ship::addCargo(Cargo* cargo) {
why? bool makes sense to me

2020-07-05 23:11 UTC, m-kop commented on shm/inc/store.hpp
> +    void setCapasity(const size_t amount) { capacity_ = amount; }
typo -> Capacity

2020-07-05 23:11 UTC, m-kop commented on shm/inc/fruit.hpp
> +    Cargo* clone() override { return new Fruit( *this);}
this memory is not deleted at all!!!

2020-07-05 23:11 UTC, m-kop commented on shm/inc/ship.hpp
> +    Cargo* getCargo(const std::string& name);
I would keep shared_ptr and change the other calls

2020-07-08 18:59 UTC, merged