Task 2.1 - added Alcohol class and overrided clone() method
Marimeiko/object-oriented-programming pull request #60
Opened 2020-07-05 07:05 UTC by Petrus9107

Left the spoil mechanism for alcohol class as well, as alcohol with time increases its price the getPrice() method should consider it and the spoil mechanism may require change as well.

2020-07-05 14:45 UTC, mariuszlisowski approved these changes

2020-07-05 23:23 UTC, m-kop requested changes

2020-07-05 23:23 UTC, m-kop commented on shm/inc/alcohol.hpp
> +    Cargo& operator-=(size_t amount);
override

2020-07-05 23:23 UTC, m-kop commented on shm/inc/alcohol.hpp
> +    Cargo* clone() override { return new Alcohol( *this);}
why not use shared_ptr here, where this memory is deleted?

2020-07-05 23:23 UTC, m-kop commented on shm/inc/fruit.hpp
> +    Cargo* clone() override { return new Fruit( *this);}
ditto

2020-07-05 23:23 UTC, m-kop commented on shm/inc/item.hpp
> +    Cargo* clone() override { return new Item( *this);}
ditto

2020-07-10 11:01 UTC, mariuszlisowski requested changes

2020-07-10 11:01 UTC, mariuszlisowski commented on shm/inc/alcohol.hpp
> +    {}
Cargo constructor needs Time*.

Alcohol(const std::string& name,
            size_t amount,
            size_t basePrice,
            size_t timeToSpoil,
            Time* time)
        : Cargo(name, amount, basePrice, time), timeToSpoil_(timeToSpoil)
    {}

2020-07-10 21:05 UTC, merged