Task 3.3 - class Store (method nextDay())
Marimeiko/object-oriented-programming pull request #66
Opened 2020-07-11 17:04 UTC by mariuszlisowski

Task created off Task_2.1a with new alcohol class implementation to simplify further merge. Test for a method added & passed (to be upgraded if needed).

2020-07-11 20:46 UTC, m-kop requested changes

2020-07-11 20:46 UTC, m-kop commented on shm/inc/store.hpp
>  class Store
class store chyba powinna dziedziczyc po Observer

2020-07-11 20:46 UTC, m-kop commented on shm/inc/store.hpp
> +    void nextDay();
dadaj override -> to powinno wyrzucic ci bledy

2020-07-11 20:46 UTC, m-kop commented on shm/test/test.cpp
> +TEST(StoreNextDay, ShouldGenerateRandomAmountOfCargo)
ten test nie ma sensu bo nic nie testuje!
wypisanie na terminalu nie ma wiekszego sensu go ktos kto go uruchomi nie wie czy terminalowy wyrzyg jest poprawany czy tez nie

2020-07-11 20:47 UTC, m-kop commented on shm/test/test.cpp
> +TEST(StoreNextDay, ShouldGenerateRandomAmountOfCargo)
zrobienie testu moze byc trudne wiec wystarczy jak "przetestujesz lokalnie" czyli ++time i czy zmienilo sie store

2020-07-11 20:48 UTC, m-kop commented on shm/inc/store.hpp
>  class Store
brkuje tez register w construtorze i remove w destruktorze

2020-07-12 10:50 UTC, mariuszlisowski commented on shm/test/test.cpp
> +TEST(StoreNextDay, ShouldGenerateRandomAmountOfCargo)
To był taki mój test, ewentualnie, żeby ktoś jak coś poprawi mógł sprawdzić, czy dalej działa. Trzeba go będzie wykasować, bo i tak nie da się sprawdzić poprawności testu - liczby pseudolosowe. To usuwam ten test.

2020-07-12 11:05 UTC, mariuszlisowski commented on shm/inc/store.hpp
>  class Store
Rzeczywiście, nie zwróciłem na to uwagi, dodałem tylko tą metodę na szybko. Dziedziczenie zrobione.

2020-07-12 11:06 UTC, mariuszlisowski commented on shm/inc/store.hpp
> +    void nextDay();
Tak, wyrzuciło. Teraz dziedziczy po Observer

2020-07-12 11:50 UTC, mariuszlisowski commented on shm/inc/store.hpp
>  class Store
Dodając addObserver() musiałem zajrzeć do Observer i okazuje się, że nie można użyć default konstruktora, bo time_ musi mieć jakiś adres obiektu klasy Time, żeby dodać obserwatora. Więc usunąłem ten konstruktor. Trzeba podać jakiś adres time_ przy budowie obiektu Store, czyli najpierw potrzebujemy obiektu Time (i nie może to być też nullptr). Testy przeszły, tylko przy ShouldHandleBuySell musiałem dodać adres &time (bo jakiś adres trzeba podać, żeby nie był nullptr - wtedy jest segmentation).

2020-07-12 11:50 UTC, mariuszlisowski commented on shm/inc/store.hpp
> +    void nextDay();
Poprawione. Dzięki!

2020-07-13 12:01 UTC, m-kop approved these changes

2020-07-13 12:02 UTC, merged